export const GET_ALL_CONSULTATION_LIST_SUCCESS = 'GET_ALL_CONSULTATION_LIST_SUCCESS'
export const GET_ALL_CONSULTATION_LIST_FAIL = 'GET_ALL_CONSULTATION_LIST_FAIL'

export const CONSULTATION_DOC_AVAILBILITY_SUCCESS= 'CONSULTATION_DOC_AVAILBILITY_SUCCESS'
export const CONSULTATION_DOC_AVAILBILITY_FAIL = 'CONSULTATION_DOC_AVAILBILITY_FAIL'

export const CONSULTATION_DOC_RESCHEDULE_SUCCESS = 'CONSULTATION_DOC_RESCHEDULE_SUCCESS'
export const CONSULTATION_DOC_RESCHEDULE_FAIL = 'CONSULTATION_DOC_RESCHEDULE_FAIL '