export const RESET = 'RESET'

export const RESET_ERROR = 'RESET_ERROR'



export const DEPT_LIST_SUCCESS = 'DEPT_LIST_SUCCESS'
export const DEPT_LIST_FAIL = 'DEPT_LIST_FAIL'

export const SET_ACTIVE_DEPT = 'SET_ACTIVE_DEPT'

export const SET_ACTIVE_DOCTOR = 'SET_ACTIVE_DOCTOR'

export const SET_DATE_TIME_TYPE = 'SET_DATE_TIME_TYPE'




export const DOCTOR_LIST_BASED_DEPT_SUCCESS = 'DOCTOR_LIST_BASED_DEPT_SUCCESS'
export const DOCTOR_LIST_BASED_DEPT_FAIL = 'DOCTOR_LIST_BASED_DEPT_FAIL'




//GET BLOGS
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS'
export const GET_BLOG_FAIL = 'GET_BLOG_FAIL'

//GEt SINGLE BLOGS
export const GET_SINGLE_BLOG_SUCCESS ='GET_SINGLE_BLOG_SUCCESS'
export const GET_SINGLE_BLOG_FAIL='GET_SINGLE_BLOG_FAIL'

//consultation booking
export const CONSULTATION_BOOKING_SUCCESS ='CONSULTATION_BOOKING_SUCCESS'
export const CONSULTATION_BOOKING_FAIL='CONSULTATION_BOOKING_FAIL'

export const UPCOMING_APPOINTMENT_SUCCESS = 'UPCOMING_APPOINTMENT_SUCCESS'
export const UPCOMING_APPOINTMENT_FAIL = 'UPCOMING_APPOINTMENT_FAIL'

export const COMPLETED_CONSULTATION_SUCCESS = 'COMPLETED_CONSULTATION_SUCCESS'
export const COMPLETED_CONSULTATION_FAIL = 'COMPLETED_CONSULTATION_FAIL'

export const SET_ACTIVE_PATIENT = 'SET_ACTIVE_PATIENT'

export const PATIENT_HISTORY_SUCCESS = 'PATIENT_HISTORY_SUCCESS'
export const PATIENT_HISTORY_FAIL = 'PATIENT_HISTORY_FAIL'


export const CONSUTATION_FILTER_SUCCESS = 'CONSUTATION_FILTER_SUCCESS'
export const CONSUTATION_FILTER_FAIL = 'CONSUTATION_FILTER_FAIL'

export const DEPT_CATEGORY_LIST_SUCCESS = 'DEPT_CATEGORY_LIST_SUCCESS'
export const DEPT_CATEGORY_LIST_FAIL = 'DEPT_CATEGORY_LIST_FAIL'

export const DEPT_BASED_CATEGORY_SUCCESS = 'DEPT_BASED_CATEGORY_SUCCESS'
export const DEPT_BASED_CATEGORY_FAIL = 'DEPT_BASED_CATEGORY_FAIL'

export const SERVICE_BASED_DEPT_SUCCESS = 'SERVICE_BASED_DEPT_SUCCESS'
export const SERVICE_BASED_DEPT_FAIL = 'SERVICE_BASED_DEPT_FAIL'

export const PROCEDURE_BASED_DEPT_SUCCESS = 'PROCEDURE_BASED_DEPT_SUCCESS'
export const PROCEDURE_BASED_DEPT_FAIL = 'PROCEDURE_BASED_DEPT_FAIL'

export const SET_REFER_SERVICE = 'SET_REFER_SERVICE'

export const SET_REFER_PROCEDURE = 'SET_REFER_PROCEDURE'

export const UPDATE_CONSULTATION_SUCCESS = 'UPDATE_CONSULTATION_SUCCESS'
export const UPDATE_CONSULTATION_FAIL = 'UPDATE_CONSULTATION_FAIL'




