export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS"
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL"

//TimeManagement 
export const ADD_TIME_SUCCESS = 'ADD_TIME_SUCCESS'
export const ADD_TIME_FAIL = 'ADD_TIME_FAIL'

//leave list
export const LEAVE_LIST_SUCCESS = 'LEAVE_LIST_SUCCESS'
export const LEAVE_LIST_FAIL = 'LEAVE_LIST_FAIL'

//leave filter
export const LEAVE_FILTER_SUCCESS = 'LEAVE_FILTER_SUCCESS'
export const LEAVE_FILTER_FAIL = 'LEAVE_FILTER_FAIL'

//Apply leave
export const APPLY_LEAVE_SUCCESS = 'APPLY_LEAVE_SUCCESS'
export const APPLY_LEAVE_FAIL = 'APPLY_LEAVE_FAIL'

//Edit Profile
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL'

//GET BLOGS
export const GET_BLOG_SUCCESS = 'GET_BLOG_SUCCESS'
export const GET_BLOG_FAIL = 'GET_BLOG_FAIL'

//GEt SINGLE BLOGS
export const GET_SINGLE_BLOG_SUCCESS ='GET_SINGLE_BLOG_SUCCESS'
export const GET_SINGLE_BLOG_FAIL='GET_SINGLE_BLOG_FAIL'

export const RESET = 'RESET'